[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Disable Next.js plugin to avoid conflicts
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disabled = true
